#include "captive_portal.h"
#include "wifi_manager.h"
#include "esp_log.h"
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <cstring>

static const char *TAG = "portal";

// Generated by tools/compress_html.py
extern "C" {
extern const uint8_t captive_portal_html_gz[];
extern const size_t captive_portal_html_gz_len;
}

namespace os32 {

static esp_err_t handle_root(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    httpd_resp_set_hdr(req, "Content-Encoding", "gzip");
    httpd_resp_send(req, reinterpret_cast<const char*>(captive_portal_html_gz),
                    captive_portal_html_gz_len);
    return ESP_OK;
}

static esp_err_t handle_scan(httpd_req_t *req)
{
    auto *mgr = static_cast<WifiManager*>(req->user_ctx);

    // Kick off async scan and wait for results (up to 10s)
    mgr->scan_networks();
    for (int i = 0; i < 100 && !mgr->is_scan_done(); i++) {
        vTaskDelay(pdMS_TO_TICKS(100));
    }

    cJSON *arr = cJSON_CreateArray();
    int count = mgr->scan_count();
    const wifi_ap_record_t *results = mgr->scan_results();
    for (int i = 0; i < count; i++) {
        const char *ssid = reinterpret_cast<const char*>(results[i].ssid);
        if (ssid[0] == '\0') continue;

        cJSON *obj = cJSON_CreateObject();
        cJSON_AddStringToObject(obj, "ssid", ssid);
        cJSON_AddNumberToObject(obj, "rssi", results[i].rssi);
        cJSON_AddNumberToObject(obj, "auth", results[i].authmode);
        cJSON_AddItemToArray(arr, obj);
    }

    char *json = cJSON_PrintUnformatted(arr);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, json);
    cJSON_free(json);
    cJSON_Delete(arr);
    return ESP_OK;
}

static esp_err_t handle_connect(httpd_req_t *req)
{
    char buf[256];
    int len = httpd_req_recv(req, buf, sizeof(buf) - 1);
    if (len <= 0) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Empty body");
        return ESP_FAIL;
    }
    buf[len] = '\0';

    cJSON *root = cJSON_Parse(buf);
    if (!root) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Invalid JSON");
        return ESP_FAIL;
    }

    cJSON *ssid = cJSON_GetObjectItem(root, "ssid");
    cJSON *pass = cJSON_GetObjectItem(root, "password");
    if (!cJSON_IsString(ssid) || !cJSON_IsString(pass)) {
        cJSON_Delete(root);
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Missing fields");
        return ESP_FAIL;
    }

    auto *mgr = static_cast<WifiManager*>(req->user_ctx);
    mgr->save_and_connect(ssid->valuestring, pass->valuestring);
    cJSON_Delete(root);

    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"ok\":true}");
    return ESP_OK;
}

static esp_err_t handle_status(httpd_req_t *req)
{
    auto *mgr = static_cast<WifiManager*>(req->user_ctx);

    const char *state_str;
    switch (mgr->state()) {
    case WifiState::CONNECTED:  state_str = "connected"; break;
    case WifiState::CONNECTING: state_str = "connecting"; break;
    case WifiState::FAILED:     state_str = "failed"; break;
    case WifiState::AP_ACTIVE:  state_str = "ap"; break;
    default:                    state_str = "idle"; break;
    }

    char ssid[33], ip[16];
    mgr->get_ssid(ssid, sizeof(ssid));
    mgr->get_ip(ip, sizeof(ip));

    cJSON *obj = cJSON_CreateObject();
    cJSON_AddStringToObject(obj, "state", state_str);
    cJSON_AddStringToObject(obj, "ssid", ssid);
    cJSON_AddStringToObject(obj, "ip", ip);

    char *json = cJSON_PrintUnformatted(obj);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, json);
    cJSON_free(json);
    cJSON_Delete(obj);
    return ESP_OK;
}

static esp_err_t handle_redirect(httpd_req_t *req)
{
    httpd_resp_set_status(req, "302 Found");
    httpd_resp_set_hdr(req, "Location", "http://192.168.4.1/");
    httpd_resp_send(req, nullptr, 0);
    return ESP_OK;
}

void CaptivePortal::start(WifiManager *wifi_mgr)
{
    wifi_mgr_ = wifi_mgr;

    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.max_uri_handlers = 8;
    config.uri_match_fn = httpd_uri_match_wildcard;

    if (httpd_start(&server_, &config) != ESP_OK) {
        ESP_LOGE(TAG, "Failed to start HTTP server");
        return;
    }

    httpd_uri_t root = {.uri = "/", .method = HTTP_GET, .handler = os32::handle_root, .user_ctx = wifi_mgr_};
    httpd_uri_t scan = {.uri = "/api/scan", .method = HTTP_GET, .handler = os32::handle_scan, .user_ctx = wifi_mgr_};
    httpd_uri_t conn = {.uri = "/api/connect", .method = HTTP_POST, .handler = os32::handle_connect, .user_ctx = wifi_mgr_};
    httpd_uri_t stat = {.uri = "/api/status", .method = HTTP_GET, .handler = os32::handle_status, .user_ctx = wifi_mgr_};
    httpd_uri_t redir = {.uri = "/*", .method = HTTP_GET, .handler = os32::handle_redirect, .user_ctx = nullptr};

    httpd_register_uri_handler(server_, &root);
    httpd_register_uri_handler(server_, &scan);
    httpd_register_uri_handler(server_, &conn);
    httpd_register_uri_handler(server_, &stat);
    httpd_register_uri_handler(server_, &redir);

    ESP_LOGI(TAG, "Captive portal started");
}

void CaptivePortal::stop()
{
    if (server_) {
        httpd_stop(server_);
        server_ = nullptr;
        ESP_LOGI(TAG, "Captive portal stopped");
    }
}

} // namespace os32
